config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  scope '(:locale)', locale: /fr/ do
    root to: 'albums#index'
    resources :albums
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates :title, :description, :author, presence: true
  belongs_to :user
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_album, only: %i[show edit update destroy]

  def index
    if params[:q].present?
      sql_query = "albums.#{params[:critere]} @@ :q"
      @albums = Album.where(sql_query, q: "%#{params[:q]}%")
    else
      @albums = Album.all
    end
    @albums = @albums.paginate(page: params[:page], per_page: 5)
  end

  def show; end

  def new
    @album = Album.new
  end

  def edit; end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    if @album.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def update
    if current_user == @album.user
      if @album.update(album_params)
        redirect_to album_path(@album)
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    if current_user == @album.user
      @album.destroy
      redirect_to albums_path
    else
      redirect_to root_path
    end
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :description, :author, :photo)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!, :set_locale

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/albums/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <div class="form">
      <%= simple_form_for @album do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :author %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/edit.html.erb
<div class="container">
  <h1><%= t(".udpate") %></h1>
  <%= render 'form', album: @album %>
  <div class="show-action">
    <div>
      <%= link_to albums_path do %>
        <i class="far fa-arrow-alt-circle-left"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/index.html.erb
<div class="container index">
  <h1>MUSIC INC.</h1>
  <%= render 'shared/form-search' %>
  <div class="row">
    <% @albums.each do |album| %>
      <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
        <%= render 'shared/card', album: album  %>
      </div>
    <% end %>
    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
      <%= link_to(new_album_path) do %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(http://res.cloudinary.com/maxime/image/upload/v1536237653/MusicIncTest/Album_cover/688550958-612x612.jpg);">
          <h4 class="text-hidden"><%= t('.add') %></h4>
        </div>
      <% end %>
    </div>
  </div>
  <%= will_paginate @albums %></div>
</div>

app/views/albums/new.html.erb
<div class="container">
  <h1><%= t(".add") %></h1>
  <%= render 'form', album: @album %>
  <div class="show-action">
    <div>
      <%= link_to albums_path do %>
        <i class="far fa-arrow-alt-circle-left"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/albums/show.html.erb
<div class="container">
  <div class="show-title">
    <h1><%= @album.author.upcase %></h1>
    -
    <h4><%= @album.title %></h4>
  </div>
  <div class="show-contenu">
    <div class="show-image-link">
      <%= cl_image_tag @album.photo, height: 300, width: 300, crop: :fill %>
    </div>
    <p><%= @album.description %></p>
  </div>
  <div class="show-action">
    <div>
      <%= link_to albums_path do %>
        <i class="far fa-arrow-alt-circle-left"></i>
      <% end %>
    </div>
    <% if current_user == @album.user %>
      <div class="show-action-autorized">
        <%= link_to edit_album_path(@album), class: 'edit' do %>
          <i class="far fa-edit"></i>
        <% end %>
        <%= link_to album_path(@album), class: 'delete', method: :delete, data: { confirm: t('.sure') } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>MusicInc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo.ico' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_card.html.erb
<%= link_to(album_path(album)) do %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= album.photo %>);">
    <h4 class="text-hidden"><%= album.author.upcase %></h4>
    <h6 class="text-hidden"><%= album.title %></h6>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_form-search.html.erb
<div class="search-form">
  <%= form_tag albums_path, method: :get do %>
    <%= label_tag(:query, t('search_by')) %>
    <%= select_tag(:critere, options_for_select([
      [t('title'), :title],
      [t('author'), :author],
      [t('description'), :description]
    ], params[:critere])) %>
    <%= text_field_tag :q, params[:q], placeholder: t('keyword') %>
    <%= submit_tag(t('search'), class: "btn") %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag("logo.png", :alt => "logo") %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">
    <% if current_user.nil? %>
      <%= link_to t("sign_in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t("sign_up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% else %>
      <%= link_to t("sign_out"), destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= image_tag("user.png", :class => "avatar dropdown-toggle", :id =>"navbar-wagon-menu", :"data-toggle" => "dropdown") %>
    <% end %>
    <a href="/" id="en"><img src="http://i64.tinypic.com/fd60km.png"/></a>
    <a href="/fr" id="fr"><img src="http://i65.tinypic.com/300b30k.png"/></a>
  </div>
</div>